---
---

```{r message=FALSE}
library(tidyverse)
library(rcv)
```

# Data prep

```{r}
year <- 2018

# data frames were scraped from bbwaa.com using scrape_data_frames.py
al.df <- read_csv(paste0("./data/", year, "_AL_CyYoung_detail.csv"), col_types=cols())
nl.df <- read_csv(paste0("./data/", year, "_NL_CyYoung_detail.csv"), col_types=cols())

rank.vals <- c("first", "second", "third", "fourth", "fifth")

colnames(al.df) <- c("name", "affiliation", "chapter", rank.vals)
colnames(nl.df) <- c("name", "affiliation", "chapter", rank.vals)

al.summary <- read_csv(paste0("./data/", year, "_AL_CyYoung_summary.csv"), col_types=cols())
nl.summary <- read_csv(paste0("./data/", year, "_NL_CyYoung_summary.csv"), col_types=cols())
```

```{r}
# fix any known data issues (errors that occur in the source data)
known_fixes <- function(vals, year) {
  for (i in 1:length(vals)) {
    if (vals[i] == "DeGrom") { vals[i] <- "deGrom" }  # this is often consistent, but it's wrong
    else if ((vals[i] == paste0("Moore", intToUtf8(160))) & (year == 2013)) { vals[i] <- "Moore" }
    else if ((vals[i] == "Fernández") & (year == 2013)) { vals[i] <- "Fernandez" }
    else if ((vals[i] == "Grienke") & (year == 2013)) { vals[i] <- "Greinke" }
    else if ((vals[i] == "Zimmerman") & (year == 2013)) { vals[i] <- "Zimmermann" }
    else if ((vals[i] == "Zimmerman") & (year == 2014)) { vals[i] <- "Zimmermann" }
    else if ((vals[i] == "Grienke") & (year == 2015)) { vals[i] <- "Greinke" }
    else if ((vals[i] == "Grenkie") & (year == 2015)) { vals[i] <- "Greinke" }
    else if ((vals[i] == "Jon Lester") & (year == 2016)) { vals[i] <- "Lester" }
    else if ((vals[i] == "Geinke") & (year == 2017)) { vals[i] <- "Greinke" }
    else if ((vals[i] == "Velander") & (year == 2018)) { vals[i] <- "Verlander" }
  }
  
  return(vals)
}

fix_df <- function(df, year, rank_col_names) {
  df <- as.data.frame(df)
  for (col in rank_col_names) {
    df[,col] <- known_fixes(df[,col], year)
  }
  
  return(as_tibble(df))
}

al.df <- fix_df(al.df, year, rank.vals)
nl.df <- fix_df(nl.df, year, rank.vals)
```

```{r}
# define a function to get the names of all players receiving votes
# (starts from column number of next_col and unions values in all columns to the right)
get_names <- function(df, next_col=4, vals=NULL) {
  df <- as.data.frame(df)
  
  if (next_col > ncol(df)) {
    # if we've reached the end of the dataframe, stop
    return(vals)
  } else {
    # take the union of the names we have so far and the names in the next column
    vals <- union(vals, df[,next_col])
    return(get_names(df, next_col=next_col+1, vals=vals))
  }
}

# get the players with votes
al.players <- get_names(al.df)
nl.players <- get_names(nl.df)

# check for possible errors
if (length(al.players) != nrow(al.summary)) {
  print("Possible error in AL data!")
}

if (length(nl.players) != nrow(nl.summary)) {
  print("Possible error in NL data!")
}
```

# MLB voting

Recreate the results from the actual voting process.

```{r results='hold'}
# set weights for how MLB tallies the votes
mlb.weights <- c(7, 4:1)

# create data frame that will store vote tallies
al.player.df <- data.frame(player=al.players)
nl.player.df <- data.frame(player=nl.players)

cols <- c("first", "second", "third", "fourth", "fifth")

for (col in cols) {
  al.player.df[,col] <- 0
  nl.player.df[,col] <- 0
}
al.player.df$total <- 0
nl.player.df$total <- 0

i <- 1
for (col in cols) {
  votes.al <- as.data.frame(al.df)[,col]
  votes.nl <- as.data.frame(nl.df)[,col]
  
  for (vote in votes.al) {
    row <- which(al.players == vote)
    al.player.df[row, col] <- al.player.df[row, col] + 1
    al.player.df[row, "total"] <- al.player.df[row, "total"] + mlb.weights[i]
  }
  for (vote in votes.nl) {
    row <- which(nl.players == vote)
    nl.player.df[row, col] <- nl.player.df[row, col] + 1
    nl.player.df[row, "total"] <- nl.player.df[row, "total"] + mlb.weights[i]
  }
  
  i <- i + 1
}

al.player.df <- al.player.df %>% 
  mutate(rank = min_rank(desc(total))) %>% 
  mutate_at("player", as.character) %>% 
  select(rank, everything()) %>% 
  arrange(rank)

nl.player.df <- nl.player.df %>% 
  mutate(rank = min_rank(desc(total))) %>% 
  mutate_at("player", as.character) %>% 
  select(rank, everything()) %>% 
  arrange(rank)

al.winner <- al.player.df %>% 
  filter(rank == 1) %>% 
  select(player) %>% 
  rename(al_winner = player)

nl.winner <- nl.player.df %>% 
  filter(rank == 1) %>% 
  select(player) %>% 
  rename(nl_winner = player)

# print(al.winner)
# print("")
# print(nl.winner)
al.player.df %>% 
  select(rank, player, total) %>% 
  head()
nl.player.df %>% 
  select(rank, player, total) %>% 
  head()
```

# Ranked choice voting

Using `rcv` package (https://github.com/cran/rcv).

```{r results='hold'}
al.rcv.df <- al.df %>% 
  select(-affiliation, -chapter) %>% 
  gather(key="vote_rank", value="candidate", first, second, third, fourth, fifth) %>% 
  mutate(vote_rank = case_when(vote_rank == "first" ~ 1,
                               vote_rank == "second" ~ 2,
                               vote_rank == "third" ~ 3,
                               vote_rank == "fourth" ~ 4,
                               vote_rank == "fifth" ~ 5)) %>% 
  rename(pref_voter_id = name) %>% 
  arrange(pref_voter_id, vote_rank)

rcv.al.out <- rcv_tally(al.rcv.df)

nl.rcv.df <- nl.df %>% 
  select(-affiliation, -chapter) %>% 
  gather(key="vote_rank", value="candidate", first, second, third, fourth, fifth) %>% 
  mutate(vote_rank = case_when(vote_rank == "first" ~ 1,
                               vote_rank == "second" ~ 2,
                               vote_rank == "third" ~ 3,
                               vote_rank == "fourth" ~ 4,
                               vote_rank == "fifth" ~ 5)) %>% 
  rename(pref_voter_id = name) %>% 
  arrange(pref_voter_id, vote_rank)

rcv.nl.out <- rcv_tally(nl.rcv.df)

rcv.al.out
rcv.nl.out
```


